### ISSUE TITLE
我改了你的代码加了个伤害计算功能

### ISSUE THREAD

**Issue by Mzzzj** [FanghanHu/Fallout76CardBuilder#1]
链接：https://pan.baidu.com/s/1JvxXpyXNMM3fc3RmtUpCzA
提取码：4shn

只加了简单的伤害计算。
算上了卡牌上明确标出来加百分之多少、加多少点伤害的卡牌和加多少倍的卡牌的值。
我的计算方法是
（拿武器伤害 + 类似铁架衣这的卡牌给的伤害值）* (1+百分比伤害卡牌的和)
不知道这样对不对，我没有类似铁架衣这样的牌也没法去测试
另一种算法是
拿武器伤害* (1+百分比伤害卡牌的和) + 类似铁架衣这的卡牌给的伤害值

**Comment by FanghanHu** [comment]
请直接发pull request， 那样我看到你的算法。谢谢。
